### ISSUE TITLE
Subtitle Language

### ISSUE THREAD

**Issue by derrick56007** [rnbguy/subscene-dl#1]
Is there any way to select the subtitle language?

thanks for the tool :)

**Comment by rnbguy** [comment]
Sorry I couldn't reply earlier. I hope you solved it on your own.

For future coders, it looks like Subscene's the language filter is set in the cookie. You should keep a persistent cookie which sets `LanguageFilter={language_id}(,{language_id})*`.

The `language_id`s can be found on the page source here - `https://u.subscene.com/filter`.
